import { NavItem, Corporate, CorporateStatus } from './types';
import { DashboardIcon, RfqIcon, MerchantIcon, CorporateIcon, ApiIcon, SettingsIcon, ReportsIcon } from './components/Icons';

export const NAV_ITEMS: NavItem[] = [
  { name: 'Dashboard', icon: DashboardIcon },
  { name: 'RFQ', icon: RfqIcon },
  { name: 'Merchant', icon: MerchantIcon },
  { name: 'Corporate', icon: CorporateIcon },
  { name: 'API', icon: ApiIcon },
];

export const SETTINGS_ITEMS: NavItem[] = [
    { name: 'Configuration', icon: SettingsIcon },
    { name: 'Management', icon: SettingsIcon },
];


export const REPORTS_ITEMS: NavItem = {
    name: 'Reports',
    icon: ReportsIcon,
    subItems: ['Merchant Report', 'Corporate Report', 'Admin Report'],
};

export const CORPORATES_DATA: Corporate[] = [
    { id: 1, companyName: 'Global Tech Inc.', regNumber: '202201012345', status: 'Approved', createdAt: '2024-07-28', investigationLog: [] },
    { id: 2, companyName: 'Synergy Innovations', regNumber: '202301054321', status: 'Cooling Period', createdAt: '2024-07-27', investigationLog: [] },
    { id: 3, companyName: 'Quantum Solutions', regNumber: '202105098765', status: 'Pending 1st Approval', createdAt: '2024-07-26', investigationLog: [] },
    { id: 4, companyName: 'Apex Industries', regNumber: '202003011223', status: 'Pending 2nd Approval', createdAt: '2024-07-25', investigationLog: [] },
    { id: 5, companyName: 'Dynamic Corp', regNumber: '201908044556', status: 'Send', createdAt: '2024-07-24', investigationLog: [] },
    { id: 6, companyName: 'Innovate LLC', regNumber: '202402017890', status: 'New', createdAt: '2024-07-29', investigationLog: [] },
    {
        id: 7, companyName: 'Legacy Holdings', regNumber: '201811116789', status: 'Rejected', createdAt: '2024-07-22',
        investigationLog: [
            { timestamp: new Date('2024-07-22T14:00:00Z').toLocaleString(), from: 'Cooling Period' as CorporateStatus, to: 'Rejected' as CorporateStatus, note: 'Initial fraud flag raised by system.' },
            { timestamp: new Date('2024-07-23T10:15:00Z').toLocaleString(), note: 'Contacted the company director for clarification. Awaiting response.' }
        ]
    },
    { id: 8, companyName: 'Future Enterprises', regNumber: '202309151357', status: 'Resolved', createdAt: '2024-07-21', investigationLog: [] },
    { id: 9, companyName: 'Pinnacle Group', regNumber: '202207202468', status: 'Closed', createdAt: '2024-07-20', investigationLog: [{ timestamp: new Date().toLocaleString(), from: 'Rejected' as CorporateStatus, to: 'Closed' as CorporateStatus, note: 'Account closed after investigation.' }] },
    { id: 10, companyName: 'Summit Partners', regNumber: '202104109753', status: 'Reopened', createdAt: '2024-07-19', investigationLog: [] },
];

export const INITIAL_CORPORATE_FORM_DATA = {
    companyName: '',
    regNumber: '',
    officeAddress1: '',
    officeAddress2: '',
    postcode: '',
    city: '',
    state: '',
    country: 'Malaysia',
    website: '',
    accountNote: '',
    subsidiaries: [],
    contacts: [
        {
            id: Date.now(),
            salutation: 'Mr',
            firstName: '',
            lastName: '',
            contactNumber: '',
            email: '',
            companyRole: '',
            systemRole: '',
        },
    ],
    billingSameAsOfficial: true,
    billingAddress1: '',
    billingAddress2: '',
    billingPostcode: '',
    billingCity: '',
    billingState: '',
    billingCountry: 'Malaysia',
    companyTIN: '',
    sstNumber: '',
    agreementFrom: '',
    agreementTo: '',
    creditLimit: '0.00',
    creditTerms: '',
    transactionFee: '',
    latePaymentInterest: '',
    whiteLabelingFee: '',
    customFeatureFee: '0.00',
    agreedToGenericTerms: false,
    agreedToCommercialTerms: false,
    firstApprovalConfirmation: false,
    secondaryApprover: {
        useExistingContact: false,
        selectedContactId: '',
        signatoryName: '',
        companyRole: '',
        systemRole: '',
        email: '',
        contactNumber: '',
    },
};


export const MOCK_FORM_DATA = {
    companyName: 'Synergy Innovations Sdn. Bhd.',
    regNumber: '202301054321',
    officeAddress1: 'Level 25, Menara Worldwide',
    officeAddress2: '198, Jalan Bukit Bintang',
    postcode: '55100',
    city: 'Kuala Lumpur',
    state: 'W.P. Kuala Lumpur',
    country: 'Malaysia',
    website: 'https://synergyinnovations.com.my',
    accountNote: 'Priority client. Focus on digital voucher solutions.',
    subsidiaries: [
        {
            id: 1,
            companyName: 'Synergy Digital Ventures',
            regNumber: '202401054321 (1509876-B)',
            officeAddress1: 'Suite 10.01, The Gardens North Tower',
            officeAddress2: '',
            postcode: '59200',
            city: 'Kuala Lumpur',
            state: 'W.P. Kuala Lumpur',
            country: 'Malaysia',
            website: 'https://synergydigital.com.my',
            accountNote: 'Handles tech development.',
        }
    ],
    contacts: [
        {
            id: 101,
            salutation: 'Mr',
            firstName: 'Ahmad',
            lastName: 'Zulkifli',
            contactNumber: '123456789',
            email: 'ahmad.z@synergyinnovations.com.my',
            companyRole: 'Managing Director',
            systemRole: 'Administrator',
        },
        {
            id: 102,
            salutation: 'Ms',
            firstName: 'Siti',
            lastName: 'Rahman',
            contactNumber: '198765432',
            email: 'siti.r@synergyinnovations.com.my',
            companyRole: 'Finance Manager',
            systemRole: 'Finance',
        }
    ],
    billingSameAsOfficial: true,
    billingAddress1: '',
    billingAddress2: '',
    billingPostcode: '',
    billingCity: '',
    billingState: '',
    billingCountry: 'Malaysia',
    companyTIN: 'C2345678901',
    sstNumber: 'SST-01-23-45678901',
    agreementFrom: '2024-08-01',
    agreementTo: '2025-07-31',
    creditLimit: '50000.00',
    creditTerms: '30',
    transactionFee: '2.5',
    latePaymentInterest: '1.5',
    whiteLabelingFee: '5.0',
    customFeatureFee: '15000.00',
    agreedToGenericTerms: false,
    agreedToCommercialTerms: false,
    firstApprovalConfirmation: false,
    secondaryApprover: {
        useExistingContact: false,
        selectedContactId: '',
        signatoryName: '',
        companyRole: '',
        systemRole: '',
        email: '',
        contactNumber: '',
    },
};

export const CORPORATE_DETAILS_DATA: Record<number, any> = {
    1: {
        ...INITIAL_CORPORATE_FORM_DATA,
        companyName: 'Global Tech Inc.',
        regNumber: '202201012345',
        officeAddress1: 'Suite 30.01, Level 30, The Gardens North Tower',
        postcode: '59200',
        city: 'Kuala Lumpur',
        state: 'W.P. Kuala Lumpur',
        website: 'https://globaltech.com',
        accountNote: 'Leading provider of cloud solutions.',
        contacts: [
            {
                id: 201,
                salutation: 'Ms',
                firstName: 'Jane',
                lastName: 'Doe',
                contactNumber: '111222333',
                email: 'jane.d@globaltech.com',
                companyRole: 'CEO',
                systemRole: 'Administrator',
            }
        ],
        creditLimit: '100000.00',
        creditTerms: '45',
        transactionFee: '1.8',
    },
    2: MOCK_FORM_DATA, // Synergy Innovations uses the main mock data
    3: {
        ...INITIAL_CORPORATE_FORM_DATA,
        companyName: 'Quantum Solutions',
        regNumber: '202105098765',
        officeAddress1: 'Block 3730, Persiaran APEC',
        postcode: '63000',
        city: 'Cyberjaya',
        state: 'Selangor',
        website: 'https://quantumsolutions.com',
        accountNote: 'Specializes in quantum computing research.',
        contacts: [
            {
                id: 301,
                salutation: 'Dr',
                firstName: 'Ben',
                lastName: 'Carter',
                contactNumber: '333444555',
                email: 'ben.c@quantumsolutions.com',
                companyRole: 'Lead Scientist',
                systemRole: 'User',
            }
        ],
        creditLimit: '75000.00',
        creditTerms: '30',
        transactionFee: '3.0',
    },
    4: {
        ...INITIAL_CORPORATE_FORM_DATA,
        companyName: 'Apex Industries',
        regNumber: '202003011223',
        officeAddress1: '123 Industrial Way',
        city: 'Shah Alam',
        state: 'Selangor',
        postcode: '40150',
        website: 'https://apexindustries.com.my',
        accountNote: 'Major manufacturing client.',
        contacts: [
            {
                id: 401,
                salutation: 'Mr',
                firstName: 'David',
                lastName: 'Chen',
                contactNumber: '178901234',
                email: 'david.c@apexindustries.com.my',
                companyRole: 'Operations Manager',
                systemRole: 'User',
            }
        ],
        creditLimit: '120000.00',
        transactionFee: '2.0',
    },
    5: {
        ...INITIAL_CORPORATE_FORM_DATA,
        companyName: 'Dynamic Corp',
        regNumber: '201908044556',
        officeAddress1: 'Level 15, Hunza Tower Gurney Paragon',
        city: 'George Town',
        state: 'Penang',
        postcode: '10250',
        website: 'https://dynamiccorp.com',
        accountNote: 'Key player in the retail sector.',
        contacts: [
            {
                id: 501,
                salutation: 'Ms',
                firstName: 'Emily',
                lastName: 'Liew',
                contactNumber: '165558899',
                email: 'emily.l@dynamiccorp.com',
                companyRole: 'Marketing Head',
                systemRole: 'Administrator',
            }
        ],
        creditLimit: '80000.00',
        transactionFee: '2.2',
    },
    6: {
        ...INITIAL_CORPORATE_FORM_DATA,
        companyName: 'Innovate LLC',
        regNumber: '202402017890',
        officeAddress1: 'G-03, SME Technopreneur Centre 3',
        city: 'Cyberjaya',
        state: 'Selangor',
        postcode: '63000',
        website: 'https://innovatellc.io',
        accountNote: 'Tech startup focusing on AI.',
        contacts: [
            {
                id: 601,
                salutation: 'Dr',
                firstName: 'Sarah',
                lastName: 'Tan',
                contactNumber: '191112233',
                email: 'sarah.t@innovatellc.io',
                companyRole: 'R&D Lead',
                systemRole: 'User',
            }
        ],
        creditLimit: '30000.00',
        transactionFee: '2.8',
    },
    7: {
        ...INITIAL_CORPORATE_FORM_DATA,
        companyName: 'Legacy Holdings',
        regNumber: '201811116789',
        officeAddress1: 'Level 20, Menara JLand',
        city: 'Johor Bahru',
        state: 'Johor',
        postcode: '80000',
        website: 'https://legacyholdings.com',
        accountNote: 'Investment holding company.',
         contacts: [
            {
                id: 701,
                salutation: 'Mr',
                firstName: 'Michael',
                lastName: 'Raj',
                contactNumber: '128889999',
                email: 'michael.r@legacyholdings.com',
                companyRole: 'Investment Analyst',
                systemRole: 'User',
            }
        ],
        creditLimit: '250000.00',
        transactionFee: '1.5',
    },
    8: {
        ...INITIAL_CORPORATE_FORM_DATA,
        companyName: 'Future Enterprises',
        regNumber: '202309151357',
        officeAddress1: 'Sublot 5, Jalan Tun Jugah',
        city: 'Kuching',
        state: 'Sarawak',
        postcode: '93350',
        website: 'https://future-ent.com',
        accountNote: 'East Malaysia regional distributor.',
        contacts: [
            {
                id: 801,
                salutation: 'Ms',
                firstName: 'Brenda',
                lastName: 'Ng',
                contactNumber: '143334455',
                email: 'brenda.n@future-ent.com',
                companyRole: 'Regional Manager',
                systemRole: 'Administrator',
            }
        ],
        creditLimit: '60000.00',
        transactionFee: '2.4',
    },
    9: {
        ...INITIAL_CORPORATE_FORM_DATA,
        companyName: 'Pinnacle Group',
        regNumber: '202207202468',
        officeAddress1: 'Level 10, Plaza Shell',
        city: 'Kota Kinabalu',
        state: 'Sabah',
        postcode: '88000',
        website: 'https://pinnaclegroup.my',
        accountNote: 'Property development giant.',
        contacts: [
            {
                id: 901,
                salutation: 'Mr',
                firstName: 'James',
                lastName: 'Wong',
                contactNumber: '137778899',
                email: 'james.w@pinnaclegroup.my',
                companyRole: 'Director',
                systemRole: 'Administrator',
            }
        ],
        creditLimit: '300000.00',
        transactionFee: '1.2',
    },
    10: {
        ...INITIAL_CORPORATE_FORM_DATA,
        companyName: 'Summit Partners',
        regNumber: '202104109753',
        officeAddress1: 'Level 50, Petronas Tower 2, KLCC',
        city: 'Kuala Lumpur',
        state: 'W.P. Kuala Lumpur',
        postcode: '50088',
        website: 'https://summitpartners.com',
        accountNote: 'Venture capital and private equity firm.',
        contacts: [
            {
                id: 1001,
                salutation: 'Ms',
                firstName: 'Patricia',
                lastName: 'Lim',
                contactNumber: '182223344',
                email: 'patricia.l@summitpartners.com',
                companyRole: 'Senior Partner',
                systemRole: 'Finance',
            }
        ],
        creditLimit: '500000.00',
        transactionFee: '1.0',
    },
};